//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libreria.Infrastructura.ScriptRecursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Scripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Scripts() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Libreria.Infrastructura.ScriptRecursos.Scripts", typeof(Scripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSERT INTO LIBRO (NAME, EDITORIAL, QUANTITYPAGES, PRICE) VALUES (@Name, @Editorial, @QuantityPages, @Price).
        /// </summary>
        internal static string LibroCommandDAO_Add {
            get {
                return ResourceManager.GetString("LibroCommandDAO-Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DELETE LIBRO WHERE ID = @id.
        /// </summary>
        internal static string LibroCommandDAO_Delete {
            get {
                return ResourceManager.GetString("LibroCommandDAO-Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UPDATE LIBRO SET NAME = @Name, EDITORIAL = @Editorial, QUANTITYPAGES = @QuantityPages, PRICE = @Price WHERE id = @id.
        /// </summary>
        internal static string LibroCommandDAO_Update {
            get {
                return ResourceManager.GetString("LibroCommandDAO-Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT ID,NAME,EDITORIAL,QUANTITYPAGES, PRICE FROM LIBRO WHERE ID = @id.
        /// </summary>
        internal static string LibroQuerysDAO_GetById {
            get {
                return ResourceManager.GetString("LibroQuerysDAO-GetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT ID, NAME, EDITORIAL, QUANTITYPAGES, PRICE FROM LIBRO WHERE PRICE &gt;= @price ORDER BY PRICE.
        /// </summary>
        internal static string LibroQuerysDAO_GetByPriceGreaterThan {
            get {
                return ResourceManager.GetString("LibroQuerysDAO-GetByPriceGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT ID, NAME, EDITORIAL, QUANTITYPAGES, PRICE FROM LIBRO.
        /// </summary>
        internal static string LiroQuerysDAO_GetAll {
            get {
                return ResourceManager.GetString("LiroQuerysDAO-GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT * FROM USUARIO WHERE USUARIO = @User AND PASSWORD = @Password.
        /// </summary>
        internal static string UsuarioDAO_GetUser {
            get {
                return ResourceManager.GetString("UsuarioDAO-GetUser", resourceCulture);
            }
        }
    }
}
